### ISSUE TITLE
Text: Chinese Characters miscoding

### ISSUE THREAD

**Issue by YifanWang1021** [Backupiseasy/ThreatPlates#162]
When the player's name contains Chinese Characters, it shows miscoding

**Comment by YifanWang1021** [comment]
My client is English environment, but I'm in servers of china. So I met this issue.

**Comment by Backupiseasy** [comment]
I guess the font for names, ... is Cabin in this case, right? This font does not support Chinese characters. That's why the font is switched to 傷害數字 or 默认. That does not work when your client is set to the enUS locale. So, I think you have to change fonts manually. 
It makes sense to have like a global setting for fonts, but right now you have to change that everywhere where fonts are used.

**Comment by YifanWang1021** [comment]
https://tva1.sinaimg.cn/large/006y8mN6ly1g6p06gk9vej31gb0u0x3f.jpg

**Comment by YifanWang1021** [comment]
> I guess the font for names, ... is Cabin in this case, right? This font does not support Chinese characters. That's why the font is switched to 傷害數字 or 默认. That does not work when your client is set to the enUS locale. So, I think you have to change fonts manually.
> It makes sense to have like a global setting for fonts, but right now you have to change that everywhere where fonts are used.

It works. The problem is solved when I change the font. Thank you
