### ISSUE TITLE
Target based highlighting also highlights non-targets if they are affected by a dot

### ISSUE THREAD

**Issue by Fail2Reap** [Backupiseasy/ThreatPlates#203]
See example of the adds also receiving the transparency of what only my target should have:
https://i.gyazo.com/a054c68f4e0d4f9d906ba78f41215b08.gif

See transparency settings below:
![image](https://user-images.githubusercontent.com/7574753/81326269-7d981d00-9091-11ea-8c17-4d5af185458a.png)
![image](https://user-images.githubusercontent.com/7574753/81326291-84269480-9091-11ea-92fb-95da70f0471d.png)

With the settings I would have expected that regardless of dots, only my actual target should have the target transparency set. 

That being said, it would be good to have a configurable option for this to choose whether you want that behavior or not, as there are use cases for both.

**Comment by Backupiseasy** [comment]
I need to test that, but do you have threat-based transparency enabled (see Threat System - Transparency). In in-combat situations, it overwrites your General transparency settings including target-based transparency.

There is a way to solve that (besides disabling threat-based transparency) if you need that.

**Comment by Fail2Reap** [comment]
I checked and threat-based transparency is enabled. You mentioned a way to solve that without disabling. Let me know what steps for that would be. Thanks!

**Comment by Backupiseasy** [comment]
You can enable additive threat-based transparency under Threat System - Transparency. It's a toggle at the bottom of the page. With this option enabled, transparendy values from General and Threat System are added instead of replacing each other. 

How should transparency work for you? From the video, I think that you want your target to have 0% transparency and all other units less than that. For that, you wouldn't need threat-based transparency. For what do you need that?

**Comment by Fail2Reap** [comment]
Sorry for the delay. IRL stuff and all that. For me it would be ideal to have my target be 0% transparency, targets I have aggro on to have 60% and targets I don't at maybe 20%. Thanks for pointing to the other settings though, I will take a look and play around a bit and see what works.
