### ISSUE TITLE
Blizz Settings > Nameplates > Vertical Overlap Keep Resetting Back to 110%

### ISSUE THREAD

**Issue by Warz78** [Backupiseasy/ThreatPlates#488]
Presently when you open Threat Plates and navigate to Blizzard Settings and then Nameplates if you have Movement Model set to "Stacking" but want to adjust the Vertical Overlap settings from the default of 110% down to a different setting (I like 35%) this setting is constantly reset and does not "stick." So I find that I need to go in and update it before each dungeon or each raid. Not sure why it doesn't just remember the setting adjustment but if that is something that could be fixed I would greatly appreciate it. Thank you.

**Comment by Backupiseasy** [comment]
This issue surfaces every few months, I feel :). Until now, it has never been related to Threat Plates, but to one the following situations:

- The setting for overlap is not stored in the TP profile, but in a WoW CVar (nameplateOverlapV). Every now and then, WoW seems to have a bug where this CVar (but also other CVars) are not saved, but reset after every reload/relog, e.g., see https://www.reddit.com/r/WowUI/comments/uci16o/help_nameplate_vertical_overlap_keeps_resetting/. 
- There are addons that restore CVars (probably because of the above bug), e.g., AdvancedInterfaceOptions. TP does not do that (at least for this CVar).

You can test the first assumption, by disabling all addons and set the CVar with
 
`/run SetCVar("nameplateOverlapV", "0.75")`

Then, reload and check what value the CVar has after the reload with

`/run GetCVar("nameplateOverlapV")`

You can also check the second assumption, by just disabling TP or any other addon and see if the CVar still resets.

**Comment by Warz78** [comment]
> This issue surfaces every few months, I feel :). Until now, it has never been related to Threat Plates, but to one the following situations:
> 
> * The setting for overlap is not stored in the TP profile, but in a WoW CVar (nameplateOverlapV). Every now and then, WoW seems to have a bug where this CVar (but also other CVars) are not saved, but reset after every reload/relog, e.g., see https://www.reddit.com/r/WowUI/comments/uci16o/help_nameplate_vertical_overlap_keeps_resetting/.
> * There are addons that restore CVars (probably because of the above bug), e.g., AdvancedInterfaceOptions. TP does not do that (at least for this CVar).
> 
> You can test the first assumption, by disabling all addons and set the CVar with
> 
> `/run SetCVar("nameplateOverlapV", "0.75")`
> 
> Then, reload and check what value the CVar has after the reload with
> 
> `/run GetCVar("nameplateOverlapV")`
> 
> You can also check the second assumption, by just disabling TP or any other addon and see if the CVar still resets.

Thank you SO much. What I did was go into AdvancedInterafaceOptions and search for "nameplateOverlapV" and set the value to .45 then restarted. Then I opened up ThreatPlates and that value was now 45% instead of 110%. No longer need to update it over and over again. Thank you!
